# Generated by Django 3.2.5 on 2021-12-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='img',
            new_name='pic',
        ),
    ]
