# Generated by Django 3.2.5 on 2021-11-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20211120_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='comments_count',
        ),
    ]
