# Generated by Django 3.2.5 on 2021-12-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20211121_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
    ]
