# Generated by Django 3.2.5 on 2021-12-02 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(limit_value='5')]),
        ),
    ]
