# Generated by Django 3.2.5 on 2021-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
